// <auto-generated />
using System;
using System.Text.Json;
using AccesoDatosApiAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccesoADatosApiAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dndsoft")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccesoDatosApiAL.Models.Personaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gremio")
                        .HasColumnType("text");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("Rasgos")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Personajes", "dndsoft");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AccesoDatosApiAL.Models.Arquero", b =>
                {
                    b.HasBaseType("AccesoDatosApiAL.Models.Personaje");

                    b.Property<double>("Precision")
                        .HasColumnType("double precision");

                    b.Property<bool>("TieneMascota")
                        .HasColumnType("boolean");

                    b.ToTable("Arqueros", "dndsoft");
                });

            modelBuilder.Entity("AccesoDatosApiAL.Models.Clerigo", b =>
                {
                    b.HasBaseType("AccesoDatosApiAL.Models.Personaje");

                    b.Property<string>("Deidad")
                        .HasColumnType("text");

                    b.Property<int>("PuntosSanacion")
                        .HasColumnType("integer");

                    b.ToTable("Clerigos", "dndsoft");
                });

            modelBuilder.Entity("AccesoDatosApiAL.Models.Guerrero", b =>
                {
                    b.HasBaseType("AccesoDatosApiAL.Models.Personaje");

                    b.Property<string>("ArmaPrincipal")
                        .HasColumnType("text");

                    b.Property<int>("Furia")
                        .HasColumnType("integer");

                    b.ToTable("Guerreros", "dndsoft");
                });

            modelBuilder.Entity("AccesoDatosApiAL.Models.Mago", b =>
                {
                    b.HasBaseType("AccesoDatosApiAL.Models.Personaje");

                    b.Property<string>("ElementoPrincipal")
                        .HasColumnType("text");

                    b.Property<int>("Mana")
                        .HasColumnType("integer");

                    b.ToTable("Magos", "dndsoft");
                });

            modelBuilder.Entity("AccesoDatosApiAL.Models.Arquero", b =>
                {
                    b.HasOne("AccesoDatosApiAL.Models.Personaje", null)
                        .WithOne()
                        .HasForeignKey("AccesoDatosApiAL.Models.Arquero", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccesoDatosApiAL.Models.Clerigo", b =>
                {
                    b.HasOne("AccesoDatosApiAL.Models.Personaje", null)
                        .WithOne()
                        .HasForeignKey("AccesoDatosApiAL.Models.Clerigo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccesoDatosApiAL.Models.Guerrero", b =>
                {
                    b.HasOne("AccesoDatosApiAL.Models.Personaje", null)
                        .WithOne()
                        .HasForeignKey("AccesoDatosApiAL.Models.Guerrero", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccesoDatosApiAL.Models.Mago", b =>
                {
                    b.HasOne("AccesoDatosApiAL.Models.Personaje", null)
                        .WithOne()
                        .HasForeignKey("AccesoDatosApiAL.Models.Mago", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
