// <auto-generated />
using System;
using AccesoADatosApi2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccesoADatosApi2.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccesoADatosApi2.Models.Personaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gremio")
                        .HasColumnType("text");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Rasgos")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Personajes");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AccesoADatosApi2.Models.Arquero", b =>
                {
                    b.HasBaseType("AccesoADatosApi2.Models.Personaje");

                    b.Property<double>("Precision")
                        .HasColumnType("double precision");

                    b.Property<bool>("TieneMascota")
                        .HasColumnType("boolean");

                    b.ToTable("Arqueros");
                });

            modelBuilder.Entity("AccesoADatosApi2.Models.Clerigo", b =>
                {
                    b.HasBaseType("AccesoADatosApi2.Models.Personaje");

                    b.Property<string>("Deidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PuntosSanacion")
                        .HasColumnType("integer");

                    b.ToTable("Clerigos");
                });

            modelBuilder.Entity("AccesoADatosApi2.Models.Guerrero", b =>
                {
                    b.HasBaseType("AccesoADatosApi2.Models.Personaje");

                    b.Property<string>("ArmaPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Furia")
                        .HasColumnType("integer");

                    b.ToTable("Guerreros");
                });

            modelBuilder.Entity("AccesoADatosApi2.Models.Mago", b =>
                {
                    b.HasBaseType("AccesoADatosApi2.Models.Personaje");

                    b.Property<string>("ElementoPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Mana")
                        .HasColumnType("integer");

                    b.ToTable("Magos");
                });

            modelBuilder.Entity("AccesoADatosApi2.Models.Arquero", b =>
                {
                    b.HasOne("AccesoADatosApi2.Models.Personaje", null)
                        .WithOne()
                        .HasForeignKey("AccesoADatosApi2.Models.Arquero", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccesoADatosApi2.Models.Clerigo", b =>
                {
                    b.HasOne("AccesoADatosApi2.Models.Personaje", null)
                        .WithOne()
                        .HasForeignKey("AccesoADatosApi2.Models.Clerigo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccesoADatosApi2.Models.Guerrero", b =>
                {
                    b.HasOne("AccesoADatosApi2.Models.Personaje", null)
                        .WithOne()
                        .HasForeignKey("AccesoADatosApi2.Models.Guerrero", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccesoADatosApi2.Models.Mago", b =>
                {
                    b.HasOne("AccesoADatosApi2.Models.Personaje", null)
                        .WithOne()
                        .HasForeignKey("AccesoADatosApi2.Models.Mago", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
